apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-hello-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Hello World</title>
    </head>
    <body>
        <h1>Hello, World!</h1>
        <p>This is served by eayar.</p>
    </body>
    </html>