apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: logging
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      serviceAccountName: filebeat
      containers:
      - name: filebeat
        image: elastic/filebeat:7.17.27
        args: ["-e", "-strict.perms=false"]
        env:
        - name: ELASTICSEARCH_HOST
          value: "http://elasticsearch.logging.svc.cluster.local:9200"
        securityContext:
          runAsUser: 0
          privileged: true  # Ensures access to `/var/lib/docker/containers`
        volumeMounts:
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: filebeat-config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
      volumes:
      - name: varlog
        persistentVolumeClaim:
          claimName: filebeat-logs-pvc
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: filebeat-config
        configMap:
          name: filebeat-config
