apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebeat-logs-pv
  labels:
    type: filebeat-logs
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/log