apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebeat-logs-pvc
  namespace: logging
spec:
  storageClassName: ""
  selector:
    matchLabels:
      type: filebeat-logs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi